server:
    port: 9010
spring:
  application:
    name: security-service
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 20KB
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${127.0.0.1:localhost}:3306/testconnect
#    username: root
#    password: 123456

#    url: jdbc:mysql://192.168.1.189:3306/timesheet
#    username: manh
#    password: Manhpd@123456
    url: jdbc:mysql://103.75.187.106:3306/timesheet
    username: manh
    password: 123aA@321

    hikari:
      connection-timeout: 6000
      maximum-pool-size: 200
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        useServerPrepStmts: true
        prepStmtCacheSqlLimit: 2048
  jpa:
    show-sql: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
eureka:
  #zuul:
  client:
   serviceUrl:
    defaultZone: ${EUREKA_URI:http://admin:admin@localhost:8761/eureka/}
#     defaultZone: ${ZUUL_URI:http://localhost:8080/}
   healthcheck:
      enabled: true
management:
   endpoint:
      health:
        show-details: always
logging:
  level:
    root: info
movie-api:
  ribbon:
    listOfServers: http://localhost:9000
#---
#server:
#  port: 3306
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: org.h2.Driver   
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://${127.0.0.1:localhost}:3306/testconnect
#    username: root
#    password: 123@Aa321
# 
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#---
#server:
#  port: 8088
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mysql://${127.0.0.1:localhost}:3306/testconnect
#    username: ${root}
#    password: ${123@Aa321}
#    driver-class-name: com.mysql.jdbc.Driver